apiVersion: ENC[AES256_GCM,data:W3k=,iv:q0BUrYZJH0UlRVmTw85NBpIVRp5O18oKepezOcO1fq8=,tag:jlVf7aHNmGYDfjZapG5UAQ==,type:str]
stringData:
    SECRET_API_KEY: ENC[AES256_GCM,data:OfzZKnf+bg==,iv:C9ZvEkTvXkxxALFmUTp4L9xULDbXAQseyE0QyTkIhb4=,tag:nCNe6DtlKz5Rc77QmtTijQ==,type:str]
kind: ENC[AES256_GCM,data:7ecmmLQt,iv:Dx72xaa6665FdnE3/iF5sAgn9LlI3SNjgbVTQAXEYdM=,tag:39ZnyE7+mE40e64feclf8Q==,type:str]
metadata:
    creationTimestamp: null
    name: ENC[AES256_GCM,data:cTcX/o7q00x/u+p+QA==,iv:SwhXuVLWryZYgiju2Ig+FsBnBQqTkIhCc7Un5rj7STo=,tag:xcN8kTPn/Wfgdg6sOKobYQ==,type:str]
sops:
    kms: []
    gcp_kms:
    -   resource_id: projects/reactiveopsio/locations/us-central1/keyRings/sops-secrets/cryptoKeys/ruby-demo
        created_at: '2019-08-02T12:33:59Z'
        enc: CiQAoslNc16Ki2ZeYv0pK+p+Smw8w9rkK6t8OqfE/8lH/NCp+yQSSADD6YD9dljdJ1ZAraB+bu6nr5TxBwmxF0lMoG3cEXkpnQmeBD0CBJClD7wWrJs9rWNyCKtL9TmLvAVKWAa+OLspqQMprEXeDA==
    lastmodified: '2019-08-02T12:34:00Z'
    mac: ENC[AES256_GCM,data:m5aAjjkgCOw6BPRoJdBn6ZkdRBmSwRWtAqp+6sqNcDLs0p6WKmZYsm08u7qRQRYQ+rGrQH/vrrYSQbeuF1afcYNGMSxbzo7VF4n2iCLg9080nulsB3JlsG6Mq3k2B1XVbuHE8xHrpk5GD48CBjyMfQxU6G229jUCAy6eINQ/pyk=,iv:Ts4+7buIYvhJ8AVZCyiFRakqCivXtBthyX1fkHuzToc=,tag:CvQwMdVEOWQ/jBmgTcW5ew==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.0.5
